name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at every 5:00 UTC
    - cron: "0 05 * * *"

jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.5
        with:
          COMMIT_MESSAGE: Readme update
          SHOW_TITLE: true
          SHOW_TIME: false
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
