name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at every 5AM UTC
    - cron: "0 5 * * *"

jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          COMMIT_MESSAGE: Update README
          SHOW_TITLE: true
          SHOW_TIME: false
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
