name: Waka Readme

on:
  push: 
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at every 7PM UTC
    - cron: "0 19 * * *"

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          COMMIT_MESSAGE: Updated README
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TIME: false
